### ISSUE TITLE
impure keyword vs. __ModelicaAssociation_Impure annotation

### ISSUE THREAD

**Issue by tbeu** [vwaurich/ExternalMemoryLib#3]
Can you please replace the impure keyword by the newly introduced __ModelicaAssociation_Impure annotation to make it working in SimulationX again. See [mo:1886](https://trac.modelica.org/Modelica/ticket/1886) for more information. Thanks.

**Comment by vwaurich** [comment]
done.

**Comment by tbeu** [comment]
Still here: https://github.com/vwaurich/ExternalMemoryLib/blob/master/ExternalMemoryLib.mo#L5

**Comment by vwaurich** [comment]
Sorry. Should be fine with the last commit

**Comment by tbeu** [comment]
Not sure if it helps to also annotate them by __ModelicaAssociation_Impure.

**Comment by tbeu** [comment]
Thanks.
